//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Throne.Login.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StrRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StrRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Throne.Login.Properties.StrRes", typeof(StrRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed..
        /// </summary>
        internal static string CMSG_AuthenticationFailed {
            get {
                return ResourceManager.GetString("CMSG_AuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name is unavailable. Please choose a different name..
        /// </summary>
        internal static string CMSG_CharacterNameUnavailable {
            get {
                return ResourceManager.GetString("CMSG_CharacterNameUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection backlog of 10 to 100 recommended..
        /// </summary>
        internal static string SMSG_BacklogRecommend {
            get {
                return ResourceManager.GetString("SMSG_BacklogRecommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuring {0} persistance..
        /// </summary>
        internal static string SMSG_ConfigPersist {
            get {
                return ResourceManager.GetString("SMSG_ConfigPersist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establishing connection with {0} on {1}.
        /// </summary>
        internal static string SMSG_IPCAuthDeviceConnection {
            get {
                return ResourceManager.GetString("SMSG_IPCAuthDeviceConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Account Service on {0}.
        /// </summary>
        internal static string SMSG_IPCAuthDeviceStartup {
            get {
                return ResourceManager.GetString("SMSG_IPCAuthDeviceStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid list host..
        /// </summary>
        internal static string SMSG_ListenHostInvalid {
            get {
                return ResourceManager.GetString("SMSG_ListenHostInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid listen port..
        /// </summary>
        internal static string SMSG_ListenPortInvalid {
            get {
                return ResourceManager.GetString("SMSG_ListenPortInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication packets contain no footer..
        /// </summary>
        internal static string SMSG_PacketFooterInvalid {
            get {
                return ResourceManager.GetString("SMSG_PacketFooterInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting {0} TCP server..
        /// </summary>
        internal static string SMSG_StartTCPListener {
            get {
                return ResourceManager.GetString("SMSG_StartTCPListener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} server listening on {1}.
        /// </summary>
        internal static string SMSG_TCPListenerStarted {
            get {
                return ResourceManager.GetString("SMSG_TCPListenerStarted", resourceCulture);
            }
        }
    }
}
