namespace Throne.World.Structures.Objects
{
    partial class Role
    {
        public enum Profession
        {
            InternTrojan = 10,
            Trojan = 11,
            VeteranTrojan = 12,
            TigerTrojan = 13,
            DragonTrojan = 14,
            TrojanMaster = 15,
            InternWarrior = 20,
            Warrior = 21,
            BrassWarrior = 22,
            SilverWarrior = 23,
            GoldWarrior = 24,
            WarriorMaster = 25,
            InternArcher = 40,
            Archer = 41,
            EagleArcher = 42,
            TigerArcher = 43,
            DragonArcher = 44,
            ArcherMaster = 45,
            InternNinja = 50,
            Ninja = 51,
            MiddleNinja = 52,
            DarkNinja = 53,
            NinjaMaster = 54,
            InternMonkSaint = 60,
            MonkSaint = 61,
            DhyanaMonkSaint = 62,
            DharmaMonkSaint = 63,
            PrajnaMonkSaint = 64,
            NirvanaMonkSaint = 65,
            InternPirate = 70,
            Pirate = 71,
            PirateGunner = 72,
            Quartermaster = 73,
            PirateCaptain = 74,
            PirateLord = 75,
            InternDragonWarrior = 80,
            DragonWarrior = 81,
            ExpertDragonWarrior = 82,
            EliteDragonWarrior = 83,
            MasterDragonWarrior = 84,
            KingDragonWarrior = 85,
            InternTaoist = 100,
            Taoist = 101,
            MetalTaoist = 112,
            MetalWizard = 113,
            MetalMaster = 114,
            MetalSaint = 115,
            WoodTaoist = 122,
            WoodWizard = 123,
            WoodMaster = 124,
            WoodSaint = 125,
            WaterTaoist = 132,
            WaterWizard = 133,
            WaterMaster = 134,
            WaterSaint = 135,
            FireTaoist = 142,
            FireWizard = 143,
            FireMaster = 144,
            FireSaint = 145,
            EarthTaoist = 152,
            EarthWizard = 153,
            EarthMaster = 154,
            EarthSaint = 155,
            GeneralTaoist = 192,
            Wizard = 193,
            Master = 194,
            Saint = 195,

            Knight = 30
        }

    }
}